#! /bin/bash

RESET='\033[0m'

CRED='\033[5;31m'

LORANGE='\033[4m'

RED='\033[1;31m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
ORANGE='\033[1;33m'

TEST='\033[5;31m'

while getopts "hud" option; do
    case $option in
    d)
        echo ""
        read -p "Remove Game-Of-Life [y/n]: " response
        echo ""
        if [[ "$response" == "y" || "$response" == "yes" || "$response" == "Y" || "$response" == "" ]]; then
            echo -e "Bye Bye Cell :("
            echo ""
            cd $(find / -name Game_of_life 2>/dev/null -type d -print -quit)
            cd ..
            rm -rf Game_of_life
            sudo rm -r /usr/local/bin/cell
            echo "Success"
        elif [[ "$response" == "n" || "$response" == "no" || "$response" == "N" ]]; then
            echo "Nothing to do."
            echo ""
        else
            echo "Invalid response."
            echo ""
        fi
        exit
        ;;
    u)
        echo ""
        echo -e "${ORANGE}update detected${RESET}"
        echo ""
        cd $(find / -name Game_of_life 2>/dev/null -type d -print -quit) && git pull
        sudo rm /usr/local/bin/cell
        rm -r Binary
        ./install/install.sh
        exit
        ;;
    h)
        echo ""
        echo -e "${ORANGE}Usage: ${GREEN}cell [${LIGHT_GREEN}optional_file_map${GREEN}] [${LIGHT_GREEN}optional_number${GREEN}]${RESET}"
        echo ""
        echo -e "${ORANGE}[-u]: ${GREEN}cell [${LIGHT_GREEN}optional_file_map${GREEN}] [${LIGHT_GREEN}optional_number${GREEN}]${RESET}"
        echo ""
        exit
        ;;
    esac
done

echo ""
cd $(find / -name Game_of_life 2>/dev/null -type d -print -quit) && ./gameoflife "$@"
echo ""
