#! /bin/bash

RESET='\033[0m'

CRED='\033[5;31m'

LORANGE='\033[4m'

RED='\033[1;31m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
ORANGE='\033[1;33m'

TEST='\033[5;31m'

while getopts "hu" option; do
    case $option in
    u)
        echo ""
        echo -e "${ORANGE}update detected${RESET}"
        echo ""
        cd $(pwd)/Game_of_life && git pull
        sudo rm /usr/local/bin/cell
        ./install/install.sh
        exit
        ;;
    h)
        echo ""
        echo -e "${ORANGE}Usage: ${GREEN}cell [${LIGHT_GREEN}optional_file_map${GREEN}] [${LIGHT_GREEN}optional_number${GREEN}]${RESET}"
        echo ""
        ;;
    *)
        echo ""
        echo -e "${ORANGE}cell: ${CRED}error:${RESET} ${ORANGE}${LORANGE}unrecognized arguments:${RESET}${RED} $@${RESET}"
        echo ""
        echo -e "${ORANGE}Usage: ${GREEN}cell [${LIGHT_GREEN}optional_file_map${GREEN}] [${LIGHT_GREEN}optional_number${GREEN}]${RESET}"
        echo ""
        ;;
    esac
done

echo ""
cd $(pwd)/Game_of_life && ./gameoflife "$@"
echo ""