#! /bin/bash

RESET='\033[0m'

CRED='\033[5;31m'

LORANGE='\033[4m'

RED='\033[1;31m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
ORANGE='\033[1;33m'

TEST='\033[5;31m'

DIR=$(find / -name Game_of_life 2>/dev/null)

while getopts "hud" option; do
    case $option in
    d)
        echo ""
        read -p "remove game of life [y/n]"
        echo ""
        if [["$response" == "y"]]; then
            echo "yes";
        elif [["$response" == "yes"]]; then
            echo "yes";
        elif [["$response" == "Y"]]; then
            echo "yes";
        elif [["$response" == ""]]; then
            echo "yes";
        elif [["$response" == "n"]]; then
            echo "no";
        elif [["$response" == "N"]]; then
            echo "no";
        elif [["$response" == "no"]]; then
            echo "no";
        else
            echo "Réponse invalide";
        fi
        ;;
    u)
        echo ""
        echo -e "${ORANGE}update detected${RESET}"
        echo ""
        cd ${DIR} && git pull
        sudo rm /usr/local/bin/cell
        ./install/install.sh
        exit
        ;;
    h)
        echo ""
        echo -e "${ORANGE}Usage: ${GREEN}cell [${LIGHT_GREEN}optional_file_map${GREEN}] [${LIGHT_GREEN}optional_number${GREEN}]${RESET}"
        echo ""
        ;;
    *)
        echo ""
        echo -e "${ORANGE}cell: ${CRED}error:${RESET} ${ORANGE}${LORANGE}unrecognized arguments:${RESET}${RED} $@${RESET}"
        echo ""
        echo -e "${ORANGE}Usage: ${GREEN}cell [${LIGHT_GREEN}optional_file_map${GREEN}] [${LIGHT_GREEN}optional_number${GREEN}]${RESET}"
        echo ""
        ;;
    esac
done

echo ""
cd ${DIR} && ./gameoflife "$@"
echo ""